version: "3"

services:
    django:
        build: .
        volumes:
            - .:/opt/services/personal_website/src
            - static_volume:/opt/services/personal_website/src/app/static
        networks:
            - nginx_network
            - database1_network
        command: bash -c "
            python app/manage.py makemigrations
            && python app/manage.py migrate
            && gunicorn --chdir app --bind 0.0.0.0:8000 django_personal_website.wsgi"
        depends_on:
            - database1

    nginx:
        image: nginx:1.13
        ports:
            - 80:80
        volumes:
            - ./config/nginx/conf.d:/etc/nginx/conf.d
            - static_volume:/opt/services/django_app/src/app/static
        depends_on:
            - django
        networks:
            - nginx_network

    database1:
        image: postgres:10
        env_file:
            - config/db/database1_env
        networks:
            - database1_network
        volumes:
            - database1_volume:/var/lib/postgresql/data

networks:
    nginx_network:
        driver: bridge
    database1_network:
        driver: bridge

volumes:
    database1_volume:
    static_volume:
